services:
  postgres:
    hostname: postgres
    image: postgres:16
    restart: always
    volumes:
      # This will create a docker volume to persist the database files in.
      # If you prefer those files to be outside of docker, you'll need to change this.
      - ./data/pgsql:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: changeme
      POSTGRES_USER: palpo
      POSTGRES_DATABASE: palpo
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U palpo"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - internal

  palpo:
    image: privoce/vocechat-matrix-palpo:main
    ports:
      - 8008:8008
      - 8448:8448
    environment:
      PALPO_CONFIG: '/var/palpo/palpo.toml'
    # PALPO_SERVER_NAME: 'matrix.palpo.im'
    # PALPO_DB_URL: 'postgres://palpo:changeme@postgres:5432/palpo'
    # PALPO_WELL_KNOWN_SERVER: matrix.palpo.im
    # PALPO_WELL_KNOWN_CLIENT: https://matrix.palpo.im
    volumes:
      - $PWD/palpo.toml:/var/palpo/palpo.toml
      # The following volumes use docker volumes, change this
      # if you prefer to have those files outside of docker.
      - $PWD/data/media:/var/palpo/media
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - internal
    restart: unless-stopped

networks:
  internal:
    attachable: true