name: Quality control

permissions:
  contents: read

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '**.rs'                 # only execute on changes to go files
      - '**/Cargo.toml'         # or dependency updates
      - '.github/workflows/**'  # or workflow changes
  push:
    branches:
      - main
    paths:
      - '**.rs'                 # only execute on changes to go files
      - '**/Cargo.toml'         # or dependency updates
      - '.github/workflows/**'  # or workflow changes

jobs:
  typos:
    name: Check typos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: rustfmt, clippy
      - name: Typos check with custom config file
        uses: crate-ci/typos@master

  test:
    strategy:
        fail-fast: false
        matrix:
          version:
            - stable
    name: Cargo check ${{ matrix.version }} - x86_64-unknown-linux-gnu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.version }}
          components: rustfmt, clippy

      - name: Install dependencies
        run: "sudo apt update && sudo apt install -y libpq-dev build-essential pkg-config"

      - name: Check build
        run: cargo check --all --bins --examples --tests

      - name: Check release build
        run: cargo check --all --bins --examples --tests --release

      # - name: Cargo test
      #   timeout-minutes: 40
      #   run: cargo test --all --all-features --no-fail-fast -- --nocapture